### ISSUE TITLE
typenames module not found

### ISSUE THREAD

**Issue by lebedov** [fjarri-attic/pyfft#1]
The file cufft/pycuda_fft.py in pycudafft 0.2 attempts to import symbols from the typenames module. This module does not exist in Python 2.6; I had to patch the file to import from the types module.

**Comment by fjarri** [comment]
Sorry, it was the module I used to handle single/double precision constants.

Was fixed in http://github.com/Manticore/pyfft/commit/453dffbc989b4631c92db43717b52955a7bdfa3a
