### ISSUE TITLE
pycudafft/kernel.mako not installed by setup.py

### ISSUE THREAD

**Issue by lebedov** [fjarri-attic/pyfft#2]
The file pycudafft/kernel.mako is not installed by default when one runs python setup.py install. Adding the following lines to the setup() call in setup.py would cause it to be installed:

```
    package_dir={'pycudafft': 'pycudafft'},
    package_data={'pycudafft': ['*.mako']},
```

**Comment by fjarri** [comment]
Thank you, fixed in http://github.com/Manticore/pyfft/commit/eb0b175d1defcf4c720991ec7bc57c9434563af3

I used a different way, because for some reason your patch still does not include kernel.mako to distributive on my system.

**Comment by lebedov** [comment]
Modifying MANIFEST.in does cause kernel.mako to be included in the source tarball generated by python setup.py sdist, but it doesn't solve the problem of kernel.mako not being installed when one runs python setup.py install.

**Comment by fjarri** [comment]
Yep, you are right. Thanks again. Fixed in http://github.com/Manticore/pyfft/commit/993e8eabede2f56f91855dcba3515e8648c5ba48 
Now it seems to be installed correctly on my system.
