### ISSUE TITLE
import error in test.py

### ISSUE THREAD

**Issue by lebedov** [fjarri-attic/pyfft#3]
When I attempted to run test/test.py in pyfft-0.3 (after installing pyfft, of course), it failed with the following message:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from pyfft.cuda import plan as FFTPlan
ImportError: cannot import name plan

**Comment by fjarri** [comment]
Test.py is obsolete and was removed in http://github.com/Manticore/pyfft/commit/9780484bd95a8741eda5462d5ea8de0fdf0abfca
