### ISSUE TITLE
pyfft on AMD

### ISSUE THREAD

**Issue by geggo** [fjarri-attic/pyfft#5]
I experienced a problem that the generated kernel generate errors with AMD OpenCL, e.g. with line
float2 a[4] = {0,0,0,0,0,0,0,0}
I think this is invalid code, but happens to compile fine with NVidia OpenCL. I suggest replacing it with
float2 a[4] = {(float2)(0.0, 0.0), (float2)(0.0, 0.0), (float2)(0.0, 0.0), (float2)(0.0, 0.0)} 

Here is a patch for kernel.make (relative to pyfft 0.3.6) that fixes this problem. With this patch pyfft passes al tests on Win7, AMD HD5850, (and still on OS X 10.6.8, Nvidia GT330M)

diff --git a/pyfft/kernel.mako b/pyfft/kernel.mako
index aca776f..9392b82 100644
--- a/pyfft/kernel.mako
+++ b/pyfft/kernel.mako
@@ -713,7 +713,8 @@

```
    ## need to fill a[] with zeros, because otherwise nvcc crashes
    ## (it considers a[] not initialized)
```
-       ${complex} a[${temp_array_size}] = {${', '.join(['0'] \* temp_array_size \* 2)}};
-       ##${complex} a[${temp_array_size}] = {${', '.join(['0'] \* temp_array_size \* 2)}};
-        ${complex} a[${temp_array_size}] = {${', '.join(['(%s)(0.0f, 0.0f)'%complex] \* temp_array_size)}};

**Comment by fjarri** [comment]
Hello geggo,

Thanks for testing pyfft on AMD — I do not have any of their videocards, so when I write code, I just hope that OpenCL works in the same way on all platforms, and sometimes it doesn't. 

As for the issue — this initialization is, in fact, not necessary; I added it just to work around an nvcc bug. Seems that it was fixed long ago, so I can probably just remove the whole initialization code. Can you please check whether

${complex} a[${temp_array_size}];

works on AMD?
