### ISSUE TITLE
pyfft does not work properly with PyOpenCL 2011.2

### ISSUE THREAD

**Issue by tnorth** [fjarri-attic/pyfft#6]
Following the example of http://packages.python.org/pyfft/, I tried a simple FFT with OpenCL (see below)
Note: pyFFT doesn't import with PyOpenCL 2011.2: reason: pyopencl has no attribute VERSION
(cl.py, line 8). I bypassed the issue by removing that check.

After that:

> > > from pyfft.cl import Plan
> > > import numpy
> > > import pyopencl as cl
> > > import pyopencl.array as cl_array
> > > ctx = cl.create_some_context(interactive=False)
> > > queue = cl.CommandQueue(ctx)
> > > plan = Plan((16, 16), queue=queue)
> > > data = numpy.ones((16, 16), dtype=numpy.complex64)
> > > gpu_data = cl_array.to_device(ctx, queue, data)
> > > print gpu_data 
> > > [[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
> > >    1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j]
> > > ...
> > >  [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
> > >    1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j]]
> > > plan.execute(gpu_data.data) 
> > > <pyopencl._cl.CommandQueue object at ...>
> > > result = gpu_data.get()
> > > print result 
> > > [[ 0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
> > >      0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
> > >      0.+0.j    0.+0.j]

What I expected:
[[ 256.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
     0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
     0.+0.j    0.+0.j] [   0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
     0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
     0.+0.j    0.+0.j]]

(A DC component equals to the sum of all the ones in the initial matrix)

**Comment by tnorth** [comment]
More infos about my configuration:
('Platform name:', 'Intel(R) OpenCL')
('Platform profile:', 'FULL_PROFILE')
('Platform vendor:', 'Intel(R) Corporation')
('Platform version:', 'OpenCL 1.1 LINUX')
('Device name:', '       Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz\x00')
('Device type:', 'CPU')
('Device memory: ', 3842, 'MB')
('Device max clock speed:', 2700, 'MHz')
('Device compute units:', 4)

pyopencl works properly, but says:

/usr/lib/python2.7/site-packages/pyopencl-2011.2-py2.7-linux-x86_64.egg/pyopencl/**init**.py:32: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz' on 'Intel(R) OpenCL' at 0x169ce70> succeeded, 

Build started
Kernel <sum> was successfully vectorized
Done.

Versions:
pyopencl-2011.2-py2.7-linux-x86_64
pyfft-0.3.6-py2.7
gcc version 4.6.1 20110908 (Red Hat 4.6.1-9) (GCC) 
intel_ocl_sdk_1.5_x64

**Comment by tnorth** [comment]
This issue is also present with the latest pyOpenCL git build.

**Comment by tnorth** [comment]
Does it _have_ to be a GPU ?

python test_all.py 
Running functionality tests...
Traceback (most recent call last):
  File "test_all.py", line 54, in <module>
    run_func(opts.test_cuda, opts.test_opencl)
  File "/tmp/test/pyfft/test/test_functionality.py", line 217, in run
    ctx = createContext(False)
  File "/tmp/test/pyfft/test/helpers.py", line 138, in createContext
    return CLContext()
  File "/tmp/test/pyfft/test/helpers.py", line 86, in **init**
    for d in p.get_devices(device_type=cl.device_type.GPU):
pyopencl.RuntimeError: clGetDeviceIDs failed: device not found

**Comment by fjarri** [comment]
> Note: pyFFT doesn't import with PyOpenCL 2011.2: reason: pyopencl has no attribute VERSION

This was a bug in pyopencl, see http://lists.tiker.net/pipermail/pyopencl/2012-February/001048.html

> Does it have to be a GPU?

Yes, at the moment it does. CPU support probably would not require much work, but from the practical point of view it is much better to use CPU-optimized FFT (numpy.fft, fftw, etc). Probably I should put a warning in Plan constructor.

**Comment by tnorth** [comment]
Thanks for your answer. For now I don't have access to a proper GPU, so I wanted to do some tests on that platform. I haven't really looked at the code, but what would need to be changed to support CPUs here ?

BTW, can these embedded graphic cards (Intel HD Graphics 3000) be considered as a GPU on linux platforms  ? (or am I missing the point, I don't know much in the field)

**Comment by fjarri** [comment]
> For now I don't have access to a proper GPU, so I wanted to do some tests on that platform. I haven't really looked at the code, but what would need to be changed to support CPUs here ?

In fact, this may be more difficult than I thought. My OpenCL platform (OSX driver) only allows workgroups of size 1, and FFT kernel's logic is based on the fact that we have large workgroups (because of extensive local memory usage). So, support for the border case with workgroups of size 1 will require a lot of changes.

On a second thought, your OpenCL platform seems to allow group sizes larger than 1 (otherwise you'd get an error during the creation of the plan), so (in theory) pyfft on your system should work as is. I am not sure why it doesn't – it may be some bug in this particular OpenCL implementation, or there may be some secific peculiarity in working with OpenCL on CPUs which I have not noticed because I did not run tests on CPU. I'll try to make CPU platform work on my Linux machine and see what I can do.

In the meantime, I guess you will have to create some stub class for FFT plan with the same interface which will just pass the array to numpy.fft. In addition, could you add the following lines to your code and tell me what they print:

```
d = ctx.get_info(cl.context_info.DEVICES)[0]
print d.get_info(cl.device_info.MAX_WORK_ITEM_SIZES)
print d.get_info(cl.device_info.MAX_WORK_GROUP_SIZE)
```

> BTW, can these embedded graphic cards (Intel HD Graphics 3000) be considered as a GPU on linux platforms ? 

No, this card does not support Cuda/OpenCL.

**Comment by tnorth** [comment]
Thank you very much:

 In [6]: print d.get_info(cl.device_info.MAX_WORK_ITEM_SIZES)
 [1024, 1024, 1024]

 In [7]: print d.get_info(cl.device_info.MAX_WORK_GROUP_SIZE)
 1024

> No, this card does not support Cuda/OpenCL.

Ok. I have a recent ATI card available, but read that the closed-source driver was terrible. Maybe I should try it anyway...

**Comment by fjarri** [comment]
I have just installed AMD OpenCL platform (http://developer.amd.com/sdks/AMDAPPSDK/downloads/Pages/default.aspx) on my Ubuntu 10.04, and I am getting correct results for the code from your initial post. Try to use it instead of Intel one (it does not require neither AMD CPU nor AMD GPU). Unfortunately, I have no way of investigating this bug on Intel OpenCL platform.

**Comment by fjarri** [comment]
> Unfortunately, I have no way of investigating this bug on Intel OpenCL platform.

Scratch that, turns out that Intel platform works on my system too, and it does give incorrect results. I'll investigate this further, and in the meantime you can use AMD platform.

**Comment by tnorth** [comment]
Wonderful, it works with the AMD OpenCL !
I don't know if it is a bug with the intel SDK or something else. If I can help with some testing on the Intel SDK, just let me know.

Many thanks.

**Comment by fjarri** [comment]
So, I managed to put together a simple kernel that behaves differently on Intel platform as compared to AMD/nVidia: http://software.intel.com/en-us/forums/showthread.php?t=103353&o=a&s=lr . Unfortunately, at this point my expertise ends, and we will have to wait for a response from Intel developers. I hope that AMD SDK will work for you until then.

**Comment by tnorth** [comment]
Thanks for following up on that.
So we'll wait for an answer to that thread. The AMD SDK works for me, but I can't use the GPU (the closed-source driver crashes the machine...). Maybe I can try and get an nvidia card. In the meantime, I need to get used to OpenCL anyway.
Thanks again!

**Comment by tnorth** [comment]
Works for me now with the AMD SDK. The bug can be closed. Thanks.
