### ISSUE TITLE
Failed to find block size for the kernel

### ISSUE THREAD

**Issue by schueppert** [fjarri-attic/pyfft#7]
Thanks for this useful tool.  Works great!   One small issue: the sample code in the documentation failed on my Macbook (OS X Lion) with the error above.  The Apple OpenCL driver provides a choice of devices (CPU and GPU) with the default being the CPU device, and the Intel CPU does not support the block size in the sample code.  I was able to solve this by changing the context definition line to:

ctx = cl.Context(dev_type=cl.device_type.GPU)

**Comment by fjarri** [comment]
Yes, OSX OpenCL platform limits the block size to 1 on CPUs for some reason. Parallel FFT algorithm relies heavily on the availability of shared memory and breaks down in this case. Possible fixes are:
1. Throw more meaningful exception (like "OSX OpenCL platform is not supported"), and fix the documentation,
2. Call numpy.fft behind the scenes,
3. Create fake shared memory in the global memory (on CPU they will be the same anyway).

I think the solution 1 is the most honest (and easiest), 2 is the fastest, and 3 'feels right' from the architectural point of view. 

I am a bit hesitant to fix it right now (it's not critical, after all), as I'm planning to merge pyfft with more general tigger module, which has more logical test framework and core, and this issue can be handled there in a more general way.

**Comment by fjarri** [comment]
The module is deprecated and won't be updated. This issue may be fixed in Reikna.
