### ISSUE TITLE
tigger or reikna ?

### ISSUE THREAD

**Issue by Nodd** [fjarri-attic/pyfft#9]
When installing pyfft from pipy, using pip, I have the following warning :

```
PyFFT is deprecated and will not be updated any more.
Its functionality is being moved to Tigger (http://tigger.publicfields.net)
```

Tigger is nowhere to be found, it should be replaced by Reinka in the message.

**Comment by fjarri** [comment]
I'm ashamed to admit that I have been aware of this for some time, but was too lazy to fix it, because it would involve re-submitting a new version to PyPi. I'll fix it now.
